# general settings
name: QuantSR_plus_T_x4_4bit   #_B32P64G4
model_type: SwinIRModel
scale: 4
num_gpu: 4
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: DF2K 
    type: PairedImageDataset
    dataroot_gt: /home/datasets/quantsr/DF2K/HR
    dataroot_lq: /home/datasets/quantsr/DF2K/LR_bicubic/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

    gt_size: 256 
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 12
    batch_size_per_gpu: 8 
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /home/datasets/quantsr/Set5/HR
    dataroot_lq: /home/datasets/quantsr/Set5/LR_bicubic/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

# network structures
network_g:
  type: QSwinIR_ours
  upscale: 4
  img_size: 64 
  window_size: 8
  img_range: 1.
  depths: [6,6,6,6,6,6,6,6]
  embed_dim: 60
  num_heads: [6,6,6,6,6,6,6,6]
  mlp_ratio: 2
  upsampler: pixelshuffledirect  

# path
path:
  pretrain_network_g: /home/pretrained_models/quantsr/002_lightweightSR_DIV2K_s64w8_SwinIR-S_x4.pth
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [ 250000, 400000, 450000, 475000 ]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 50
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true

# logging settings
logger:
  print_freq: 5000
  save_checkpoint_freq: !!float 5000
  use_tb_logger: true
  wandb:
    project: ~ 
    resume_id: ~ 

# dist training settings
dist_params:
  backend: nccl
  port: 29500

distill:
  distill: True
  pretrain_network_g: ~
  strict_load_g: True
  network_teacher:
    type: EDSR
    num_in_ch: 3
    num_out_ch: 3
    num_feat: 256
    num_block: 32
    upscale: 4
    res_scale: 0.1
    img_range: 255.
    rgb_mean: [0.4488, 0.4371, 0.4040]
